### PR TITLE
Sort imports with Isort.

### PR DESCRIPTION
**Pull request by TheQuinbox**
## Link to issue number:
None
### Summary of the issue:
In Pep-8, it's convention to sort imports a certain way. There's a tool (Isort)  that does this for us.
### Description of how this pull request fixes the issue:
Added Isort to requirements-dev, and ran it on the entire codebase.
### Testing performed:
None necessary (Isort doesn't change functionality), similar to Black.
### Known issues with pull request:
None

### CODE REVIEW

**Comment by mush42** [comment]
Hi @TheQuinbox 

I tried isort last week and after running it on the source code bookworm failed to run.

We've some problems with circular imports, unless we fix those, the tool will, actually, effect the functionality.

I'll be keeping an eye on this PR.

Best

**Comment by TheQuinbox** [comment]
@mush42, I don't actually see how that's possible. AFAIK, Isort just moves code around (puts line breaks, indents extra long lines, etc). None of that should cause circular imports.

I would test, but I'm currently unable to run Bookworm from source for... some reason. What files were causing the problem?

**Comment by pauliyobo** [comment]
Hello.
@TheQuinbox I was able to solve the circular import issues, or at least solve enough to make bookworm run in a test branch.
How would you like to progress on this?

**Comment by mush42** [comment]
@pauliyobo  Is it  safe to re-run isort on the code base without reservations?

**Comment by pauliyobo** [comment]
@mush42 It should be yes.
Although I am personally thinking that we should probably automate this process with something like pre-commit in order to maintain consistency. Would you have any problem with this? I am happy to open an issue if so.

**Comment by mush42** [comment]
No. I have no problems with adding pre-commit. 
Do you have time to add this? Or should I add it myself?

**Comment by pauliyobo** [comment]
I do. I'll add this tomorrow.

**Pull request merged**
