### PR TITLE
Bookworm can now be used as a CLI application

### LINKED ISSUE #230: Command line arguments?
bookworm.exe 

executes bookworm

bookworm.exe mypdf.pdf

does nothing.

Either way, even opening the pdf I see nothing except the TOC.

### PR DESCRIPTION
**Pull request by pauliyobo**
fixes #230 
This PR basically makes bookworm usable as a CLI app.
To be clear, when compiled in windowed mode, commandline args would still work, but you would have not received any feedback due to the fact that windowed mode does not provide you with any I/O stream. Up until now,  bookworm would redirect sys.stdout and sys.stderr to os.devnull, this however would not allow the user to receive feedback about the command supplied.
It is now possible to treat bookworm as a CLI app, pyinstaller now builds it as a console app as well. At runtime, we hide the extra console window bookworm pops up through ctypes.

### CODE REVIEW

**Comment by mush42** [comment]
@pauliyobo  impressive work.

**Comment by DraganRatkovich** [comment]
Hello,

@pauliyobo Is it ready to merge?

**Comment by cary-rowen** [comment]
cc @pauliyobo @mush42 
After this PR is merged, the software cannot be launched in GUI.

**Comment by cary-rowen** [comment]
After I uninstalled the old version and then reinstalled the build of this PR, bookworm ran as expected, but the command line window was not hidden.

**Comment by mush42** [comment]
I confirm what @cary-rowen reported. There is an issue where a command window is briefly shown before the shim code kicks in. This is very disturbing for users. I think there is no way to work around this unless we use the window-less mode of Python.

**Comment by mush42** [comment]
If showing stdout is important for some users, we can use WXPython's stdout/stderr window for that, only in if the app is running in debug mode.
For commandline help, we can use the approach used by other gui apps that have a commandline interface, by showing a message dialog when the app is invoked with some cmd arguments.

**Comment by mush42** [comment]
I'll revert the merge and keep the PR open for further discussion

**Comment by pauliyobo** [comment]
Hmm yeah.
At this point then I suppose the best thing is to show a dialog in response to user input. I'll work on this as time permits, but hopefully I'll have something soon.

**Comment by mush42** [comment]
Thanks!
That would be great.

**Pull request merged**
