### PR TITLE
Updates to the readme to replace note-taking with comments, fixed license and website URL in user guide.

### PR DESCRIPTION
**Pull request by DraganRatkovich**

### CODE REVIEW

**Comment by cary-rowen** [comment]
HI @DraganRatkovich 
thanks for your efforts, The URL should also be updated.
For example, replace 'github.com/mush42/bookworm' with 'github.com/blindpandas/bookworm'
Also, the page fails with: 'mush42.github.io/bookworm'
Grateful

**Comment by DraganRatkovich** [comment]
Hello @cary-rowen Thanks for the info, I've updated the file and pushed the new commit to the pull request and also updated the title to match the changes.

**Comment by mush42** [comment]
@DraganRatkovich  Thanks for your efforts.

**Comment by DraganRatkovich** [comment]
@mush42 You're welcome

**Pull request merged**
