### PR TITLE
Epub documents chapters will be ordered according to the document's spine where applicable

### LINKED ISSUE #243: Wrong chapter order when reading epub file (chapter 29, chapter 3, chapter 30.
## Describe the Problem
I was reading a book and I was on chapter 29, then chapter 3 came up, then chapter 30.
I will provide more details in how to reproduce

## To Reproduce
Open the linked file in this issue.
Go to reading percentage 69, you will be at the end of chapter 29. Alternatively use H and shift H to jump via headings.

You will notice that if you press down arrow at this point you will be on chapter 3 instead of chapter 30.
At the end of chapter 3, chapter 30 comes up.
It seems as though it's getting the wrong order, as in a Mac or Unix like environment instead of windows, because chapter is not 03, but just number 3.

## Expected behavior

Read in the correct chapter order.

## If the problem is related to a file, indicate the file you have opened

https://drive.oriolgomez.com/f/4ec6e05626d34198a7b7/

## Desktop (please complete the following information):

Windows 11, Spanish localization.
Bookworm latest version (no updates found).
 - Recent settings you may have changed in Bookworm [e.g. changed the speech settings]: None

### PR DESCRIPTION
**Pull request by pauliyobo**
## Link to issue number:
fixes #243 
### Summary of the issue:
Basically whenever an epub document would have chapters with, say, a different naming scheme, such as roman numbers, their order would be totally inconsistent with what the result should be.
### Description of how this pull request fixes the issue:
Since epub chapters are files in a folder, their current order would follow the OS filesystem ordering scheme rather than the book.
This PR essentially compares the files to be included in the book to render and if necessary they are adjusted according to the spine structure, which we always assume to be correct.
### Testing performed:
Unit tests 
### Known issues with pull request:
None

@ogomez92 would you mind trying this version as soon as it builds?
You will probably have to clear the document cache for the fix to take effect.
Also, in the testsuite I have added the roman.epub file you attached in the issue. If this is a problem, please let me know and I will find something else to use instead.

### CODE REVIEW

**Comment by ogomez92** [comment]
Hi.
It's no problem, you can use this, it's a book by Michael connelly. It's in spanish though.

I'll try as soon as it builds but your appveyor build failed. can you check?

Thanks.

**Comment by cary-rowen** [comment]
@pauliyobo 
Can you fix the build error?

**Comment by ogomez92** [comment]
Any news on this issue? Is there some input you need from me to generate
the build?

**Comment by pauliyobo** [comment]
Hello
I apologize for the delay, it has been a busy week at work.
@ogomez92 now that #234 has been merged you can grab the artifacts from the actions page. Please let me know if it works on your end as well before I merge.

**Comment by ogomez92** [comment]
This build fails because it can't find 2in32api, for some reason.
Unhandled exception in script.
Traceback (most recent call last):
  File
"Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py",
line 46, in <module>
  File
"Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py",
line 25, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "win32com\__init__.py", line 9, in <module>
ImportError: DLL load failed while importing win32api: No se encontró el
proceso especificado.

that last bit translates to the typical OSError when a process isn't found.

**Comment by ogomez92** [comment]
[06 El_vuelo_del_angel_Michael_Connelly.zip](https://github.com/blindpandas/bookworm/files/14079650/06.El_vuelo_del_angel_Michael_Connelly.zip)
Hi,
OK nthat was strange, it seemed to be an error when replacing the new over the old one, but it worked.
The problem is that the issue seems to still be there with some files.
I cleared the document cache and deleted the database folder in the user-config just to double checked.
With the file I'm sending you it still happens, can you check?

Thanks.

**Comment by pauliyobo** [comment]
Hello. Do you mean the first file? I happen to have lost it, would you mind providing another link?
Thanks.

**Comment by ogomez92** [comment]
no I mean the file I attached to my previous comment.
https://drive.oriolgomez.com/f/19fdced667c142cab042/
https://drive.oriolgomez.com/f/19fdced667c142cab042/

**Comment by pauliyobo** [comment]
Thank you. Can you try now? You'll have to clear the cache again.

**Comment by pauliyobo** [comment]
Hello,
@ogomez92 just checking to understand if the PR solves your issue or if there are still things that don't work.

**Comment by ogomez92** [comment]
Hi.
All is well now, it works perfectly.

**Pull request merged**
