### PR TITLE
Created a Telegram group for Bookworm and added a link to it in the Readme file, Updated Russian localization

### PR DESCRIPTION
**Pull request by DraganRatkovich**
Anyone can join the Telegram group and discuss, help others about Bookworm

### CODE REVIEW

**Comment by Cambridgeport90** [comment]
Nice going... think I'll end up being one of the first to join.

From: DraganRatkovich ***@***.***>
Sent: Saturday, April 30, 2022 10:39 AM
To: blindpandas/bookworm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [blindpandas/bookworm] Created a Telegram group for Bookworm and added a link to it in the Readme file (PR #153)


Anyone can join the Telegram group and discuss, help others about Bookworm

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/blindpandas/bookworm/pull/153

Commit Summary

  *   ffea074<https://github.com/blindpandas/bookworm/pull/153/commits/ffea074bf39cfcf0074b8d0e05e50168eda5620c> Created a Telegram group for Bookworm and added a link to it in the Readme file

File Changes

(1 file<https://github.com/blindpandas/bookworm/pull/153/files>)

  *   M readme.md<https://github.com/blindpandas/bookworm/pull/153/files#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15> (6)

Patch Links:

  *   https://github.com/blindpandas/bookworm/pull/153.patch
  *   https://github.com/blindpandas/bookworm/pull/153.diff

-

**Comment by DraganRatkovich** [comment]
@Cambridgeport90 You can join from [this](https://t.me/+_qcuopCgPopkOGJi) link

**Comment by Cambridgeport90** [comment]
Just tried it... Get an error that the group chat doesn't seem to exist... using Unigram to join, if that makes a difference.

**Comment by DraganRatkovich** [comment]
@Cambridgeport90 Interesting, I can open the link without problems…

**Comment by DraganRatkovich** [comment]
@Cambridgeport90 I can also add you if you still can't join. Just write me your username via [my Telegram](https://t.me/DraganRatkovich)

**Comment by Cambridgeport90** [comment]
I’ll do that. Definitely in a little while, because I’m heading out in a few minutes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DraganRatkovich** [comment]
Hello @Cambridgeport90
Recently, on one forum, a user reported that when following a hyperlink, he had the same error as you had. Right now I'm pasting a regular link, no hyperlink and please let me know if you can join.
https://t.me/+_qcuopCgPopkOGJi

**Comment by Cambridgeport90** [comment]
Interesting. I will let you know when I get home from work and actually have access to a proper telegram client.

**Comment by DraganRatkovich** [comment]
@Cambridgeport90 The Telegram group is now public, you can search for it by username @bookworm_official

**Comment by DraganRatkovich** [comment]
@mush42 All commits failed, please do something.

**Comment by DraganRatkovich** [comment]
@pauliyobo Thanks for the pull request. Yes, I also noticed AppVeyor crashes, hopefully they will be fixed.

**Comment by Cambridgeport90** [comment]
What error did the failure give?

**Pull request merged**
